name: demo
services:
    web:
        build: .
        repo:
            name: cameronmaske/flask-web
groups:
    web:
        size: t1.m
        loadbalance:
            - "80:80"
        scale: 2
        regions:
            - us-east-1
            - us-west-1
        services:
            - web