name: demo
services:
    web:
        build: .
        scale: 1
        ports:
            - "80:5000"
        repo:
            name: cameronmaske/flask-web
region: us-east-1
groups:
    web:
        size: t1.micro
        scale: 1
        ports:
            public:
                - "80"
        services:
            - web