name: demo
services:
    web:
        build: .
        loadbalance:
            - "5000"
        repo:
            name: cameronmaske/flask-web
groups:
    web:
        size: t1.micro
        loadbalance:
            - "80:5000"
        scale: 1
        regions:
            - us-east-1
        services:
            - web