language: python
python:
  - "2.7"
install:
    - "pip install -e ."
    - "pip install -r requirements-dev.txt"
script:
    - py.test --cov skipper --cov-report term-missing
after_success:
  - coveralls